---
- name: Deploy python app
  hosts: all
  become: yes
  vars:
    container_name: python-metrics-app
    container_port: 8080
    host_port: 8080
    container_mode: false

  roles:
    - role: python-metrics-app